default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV['DATABASE_HOST'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: dummy_development

test:
  <<: *default
  database: dummy_test

production:
  <<: *default
  database: dummy_production
  username: dummy
  password: <%= ENV['DUMMY_DATABASE_PASSWORD'] %>
